TERRASSA VILLAGE DATA CLEANING

COMBINING MOMO statements

In [1]:
# Data Manipulation Libraries
import pandas as pd
import numpy as np

# Visualisation Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning & Evaluation Libraries
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split 

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Statistical Libraries
from scipy.stats import pearsonr

In [11]:
from pathlib import Path
import pandas as pd

# 1. Point to your current directory
current_dir = Path(".")

# 2. Find all CSV files in this folder
csv_files = list(current_dir.glob("*.csv"))

print(f"Found {len(csv_files)} CSV files: {[f.name for f in csv_files]}")
print(f"The number of csv files available: {len(csv_files)} CSV files\n")

# 3. Load all CSVs into a list of DataFrames
df_list = [pd.read_csv(file) for file in csv_files]

# 4. Inspect the first DataFrame in the list to make sure it looks right
print("Showing the first few rows of the first loaded file:")
df_list[0].head()

Found 12 CSV files: ['10th march to 20th march.csv', '16th April to 23rd april 2026.csv', '1st Jan to 20th feb 2026.csv', '20th feb to 26th feb.csv', '20th to 25th march 2026.csv', '23rd April to 30th april.csv', '25th to 28th march.csv', '26th feb to 3rd march 2026.csv', '28th to 31st March.csv', '31st march to 8th april.csv', '3rd march to 10th march 2026.csv', '8th to 16th Apri.csv']
The number of csv files available: 12 CSV files

Showing the first few rows of the first loaded file:

,Id,External id,Date,Status,Type,Provider category,From,From name,From handler name,To,...,Coupon,Currency.13,Amount,Currency.14,Balance,Currency.15,External amount,Currency.16,External FX rate,External service provider
0,26819789562,NaN,2026-03-20 17:50:30,Successful,Payment,NaN,FRI:250784897438/MSISDN,Aline Kayitesi,Aline Kayitesi,FRI:21327076/MM,...,NaN,NaN,1000,RWF,1418386.0,RWF,NaN,NaN,NaN,NaN
1,26814154535,NaN,2026-03-20 13:10:59,Successful,Payment,NaN,FRI:250788312174/MSISDN,Gihana Manasseh WANDERA,Gihana Manasseh WANDERA,FRI:21327076/MM,...,NaN,NaN,13000,RWF,1417386.0,RWF,NaN,NaN,NaN,NaN
2,26813179874,NaN,2026-03-20 12:23:28,Successful,Payment,NaN,FRI:250788301339/MSISDN,Andre MUNYAKAZI,Andre MUNYAKAZI,FRI:21327076/MM,...,NaN,NaN,3000,RWF,1404451.0,RWF,NaN,NaN,NaN,NaN
3,26807177253,NaN,2026-03-20 02:17:21,Successful,Payment,NaN,FRI:250788306609/MSISDN,Emmanuel MUSHINZIMANA,Emmanuel MUSHINZIMANA,FRI:21327076/MM,...,NaN,NaN,260000,RWF,1401466.0,RWF,NaN,NaN,NaN,NaN
4,26807146138,NaN,2026-03-20 01:50:34,Successful,Payment,NaN,FRI:250792416929/MSISDN,Jaques NIZEYIMANA,Jaques NIZEYIMANA,FRI:21327076/MM,...,NaN,NaN,2000,RWF,1142766.0,RWF,NaN,NaN,NaN,NaN

In [13]:
from pathlib import Path
import pandas as pd

# 1. Point to your current directory
current_dir = Path(".")

# 2. Find all CSV files in this folder
csv_files = list(current_dir.glob("*.csv"))

print(f"Found {len(csv_files)} CSV files: {[f.name for f in csv_files]}")
print(f"The number of csv files available: {len(csv_files)} CSV files\n")

# 3. Load all CSVs into a list of DataFrames
df_list = [pd.read_csv(file) for file in csv_files]


# 4. Loop through the list to inspect every single DataFrame
# 'zip' lets us pair the file name with its corresponding DataFrame
for file_path, df in zip(csv_files, df_list):
    print("="*50)
    print(f"Showing the first few rows of file: {file_path.name}")
    print("="*50)
    print(df.head())
    print("\n")  # Adds a blank line between dataframes for readability

Found 12 CSV files: ['10th march to 20th march.csv', '16th April to 23rd april 2026.csv', '1st Jan to 20th feb 2026.csv', '20th feb to 26th feb.csv', '20th to 25th march 2026.csv', '23rd April to 30th april.csv', '25th to 28th march.csv', '26th feb to 3rd march 2026.csv', '28th to 31st March.csv', '31st march to 8th april.csv', '3rd march to 10th march 2026.csv', '8th to 16th Apri.csv']
The number of csv files available: 12 CSV files

==================================================
Showing the first few rows of file: 10th march to 20th march.csv
==================================================
            Id External id                 Date      Status     Type  \
0  26819789562         NaN  2026-03-20 17:50:30  Successful  Payment
1  26814154535         NaN  2026-03-20 13:10:59  Successful  Payment
2  26813179874         NaN  2026-03-20 12:23:28  Successful  Payment
3  26807177253         NaN  2026-03-20 02:17:21  Successful  Payment
4  26807146138         NaN  2026-03-20 01:50:34  Successful  Payment

  Provider category                     From                From name  \
0               NaN  FRI:250784897438/MSISDN           Aline Kayitesi
1               NaN  FRI:250788312174/MSISDN  Gihana Manasseh WANDERA
2               NaN  FRI:250788301339/MSISDN          Andre MUNYAKAZI
3               NaN  FRI:250788306609/MSISDN    Emmanuel MUSHINZIMANA
4               NaN  FRI:250792416929/MSISDN        Jaques NIZEYIMANA

         From handler name               To  ... Coupon Currency.13  Amount  \
0           Aline Kayitesi  FRI:21327076/MM  ...    NaN         NaN    1000
1  Gihana Manasseh WANDERA  FRI:21327076/MM  ...    NaN         NaN   13000
2          Andre MUNYAKAZI  FRI:21327076/MM  ...    NaN         NaN    3000
3    Emmanuel MUSHINZIMANA  FRI:21327076/MM  ...    NaN         NaN  260000
4        Jaques NIZEYIMANA  FRI:21327076/MM  ...    NaN         NaN    2000

  Currency.14    Balance Currency.15 External amount  Currency.16  \
0         RWF  1418386.0         RWF             NaN          NaN
1         RWF  1417386.0         RWF             NaN          NaN
2         RWF  1404451.0         RWF             NaN          NaN
3         RWF  1401466.0         RWF             NaN          NaN
4         RWF  1142766.0         RWF             NaN          NaN

   External FX rate External service provider
0               NaN                       NaN
1               NaN                       NaN
2               NaN                       NaN
3               NaN                       NaN
4               NaN                       NaN

[5 rows x 54 columns]


==================================================
Showing the first few rows of file: 16th April to 23rd april 2026.csv
==================================================
            Id  External id                 Date      Status     Type  \
0  27493078364          NaN  2026-04-23 18:07:38  Successful  Cash in
1  27492671865          NaN  2026-04-23 17:53:28  Successful  Payment
2  27492622080          NaN  2026-04-23 17:51:40  Successful  Payment
3  27490816334          NaN  2026-04-23 16:33:59  Successful  Payment
4  27490796492          NaN  2026-04-23 16:32:59  Successful  Cash in

  Provider category                     From  \
0               NaN  FRI:250781028803/MSISDN
1               NaN  FRI:250788609851/MSISDN
2               NaN  FRI:250788871711/MSISDN
3               NaN  FRI:250784762931/MSISDN
4               NaN  FRI:250781028803/MSISDN

                                           From name  \
0  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd
1                              Antoine NGIRUWONSANGA
2                                   Eugene UWUMUKIZA
3                          Ephantus Ndirangu Wanderi
4  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd

                                   From handler name                       To  \
0  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd  FRI:250792043157/MSISDN
1                              Antoine NGIRUWONSANGA          FRI:21327076/MM
2                                   Eugene UWUMUKIZA          FRI:21327076/MM
3                          Ephantus Ndirangu Wanderi          FRI:21327076/MM
4  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd  FRI:250785634968/MSISDN

   ... Coupon Currency.13 Amount Currency.14   Balance Currency.15  \
0  ...    NaN         NaN  -1000         RWF  440548.0         RWF
1  ...    NaN         NaN  31000         RWF  441548.0         RWF
2  ...    NaN         NaN   9500         RWF  410703.0         RWF
3  ...    NaN         NaN  25000         RWF  401250.0         RWF
4  ...    NaN         NaN  -4500         RWF  376375.0         RWF

  External amount  Currency.16  External FX rate External service provider
0             NaN          NaN               NaN                       NaN
1             NaN          NaN               NaN                       NaN
2             NaN          NaN               NaN                       NaN
3             NaN          NaN               NaN                       NaN
4             NaN          NaN               NaN                       NaN

[5 rows x 54 columns]


==================================================
Showing the first few rows of file: 1st Jan to 20th feb 2026.csv
==================================================
            Id External id                 Date      Status     Type  \
0  26227217723         NaN  2026-02-20 22:04:56  Successful  Payment
1  26224891549         NaN  2026-02-20 20:15:24  Successful  Cash in
2  26222302726         NaN  2026-02-20 19:00:05  Successful  Payment
3  26215205499         NaN  2026-02-20 14:26:07  Successful  Payment
4  26213759829         NaN  2026-02-20 13:17:17  Successful  Payment

  Provider category                     From  \
0               NaN  FRI:250780660346/MSISDN
1               NaN  FRI:250781028803/MSISDN
2               NaN  FRI:250794687038/MSISDN
3               NaN  FRI:250788307395/MSISDN
4               NaN  FRI:250784070237/MSISDN

                                           From name  \
0                                     Andrew RUKUNDO
1  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd
2                               Immaculee UWIMBABAZI
3                                      Paul UMUKUNZI
4                           Jean Claude MBARUSHIMANA

                                   From handler name               To  ...  \
0                                     Andrew RUKUNDO  FRI:21327076/MM  ...
1  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd  FRI:21230004/ID  ...
2                               Immaculee UWIMBABAZI  FRI:21327076/MM  ...
3                                      Paul UMUKUNZI  FRI:21327076/MM  ...
4                           Jean Claude MBARUSHIMANA  FRI:21327076/MM  ...

  Coupon Currency.13  Amount Currency.14 Balance Currency.15 External amount  \
0    NaN         NaN   77000         RWF  529102         RWF             NaN
1    NaN         NaN   -8500         RWF  452487         RWF             NaN
2    NaN         NaN   14000         RWF  460987         RWF             NaN
3    NaN         NaN   28500         RWF  447057         RWF             NaN
4    NaN         NaN  100000         RWF  418699         RWF             NaN

   Currency.16  External FX rate External service provider
0          NaN               NaN                       NaN
1          NaN               NaN                       NaN
2          NaN               NaN                       NaN
3          NaN               NaN                       NaN
4          NaN               NaN                       NaN

[5 rows x 54 columns]


==================================================
Showing the first few rows of file: 20th feb to 26th feb.csv
==================================================
            Id  External id                 Date      Status     Type  \
0  26357189525          NaN  2026-02-26 23:34:40  Successful  Payment
1  26356698470          NaN  2026-02-26 22:24:35  Successful  Payment
2  26356646950          NaN  2026-02-26 22:19:44  Successful  Payment
3  26356529159          NaN  2026-02-26 22:09:28  Successful  Payment
4  26355303461          NaN  2026-02-26 20:56:59  Successful  Payment

   Provider category                     From              From name  \
0                NaN  FRI:250783589235/MSISDN        Eric BYIRINGIRO
1                NaN  FRI:250790134719/MSISDN       Chris NGABONZIZA
2                NaN  FRI:250783589235/MSISDN        Eric BYIRINGIRO
3                NaN  FRI:250788403806/MSISDN      Janvier RWAKAGABO
4                NaN  FRI:250780821031/MSISDN  Joy Sandrine GIRAMATA

       From handler name               To  ... Coupon Currency.13 Amount  \
0        Eric BYIRINGIRO  FRI:21327076/MM  ...    NaN         NaN   4500
1       Chris NGABONZIZA  FRI:21327076/MM  ...    NaN         NaN   3000
2        Eric BYIRINGIRO  FRI:21327076/MM  ...    NaN         NaN  30000
3      Janvier RWAKAGABO  FRI:21327076/MM  ...    NaN         NaN  54000
4  Joy Sandrine GIRAMATA  FRI:21327076/MM  ...    NaN         NaN  31500

  Currency.14  Balance Currency.15 External amount  Currency.16  \
0         RWF  1157184         RWF             NaN          NaN
1         RWF  1152706         RWF             NaN          NaN
2         RWF  1149721         RWF             NaN          NaN
3         RWF  1119871         RWF             NaN          NaN
4         RWF  1066141         RWF             NaN          NaN

   External FX rate External service provider
0               NaN                       NaN
1               NaN                       NaN
2               NaN                       NaN
3               NaN                       NaN
4               NaN                       NaN

[5 rows x 54 columns]


==================================================
Showing the first few rows of file: 20th to 25th march 2026.csv
==================================================
            Id  External id                 Date      Status     Type  \
0  26920688975          NaN  2026-03-25 23:18:31  Successful  Payment
1  26920145919          NaN  2026-03-25 22:00:38  Successful  Payment
2  26920126282          NaN  2026-03-25 21:58:44  Successful  Payment
3  26918506085          NaN  2026-03-25 20:20:50  Successful  Payment
4  26914870358          NaN  2026-03-25 18:22:39  Successful  Payment

   Provider category                     From                From name  \
0                NaN  FRI:250785713120/MSISDN             Cedric SHEMA
1                NaN  FRI:250780058969/MSISDN  Ange Claudia HARERIMANA
2                NaN  FRI:250780058969/MSISDN  Ange Claudia HARERIMANA
3                NaN  FRI:250788818492/MSISDN    Aime Emmanuel KAVUTSE
4                NaN  FRI:250783153025/MSISDN       Jean Wyclif KAJUGA

         From handler name               To  ... Coupon Currency.13 Amount  \
0             Cedric SHEMA  FRI:21327076/MM  ...    NaN         NaN   2000
1  Ange Claudia HARERIMANA  FRI:21327076/MM  ...    NaN         NaN    500
2  Ange Claudia HARERIMANA  FRI:21327076/MM  ...    NaN         NaN  27000
3    Aime Emmanuel KAVUTSE  FRI:21327076/MM  ...    NaN         NaN  21500
4       Jean Wyclif KAJUGA  FRI:21327076/MM  ...    NaN         NaN  28000

   Currency.14  Balance  Currency.15  External amount  Currency.16  \
0          RWF  2688018          RWF              NaN          NaN
1          RWF  2686028          RWF              NaN          NaN
2          RWF  2685528          RWF              NaN          NaN
3          RWF  2658663          RWF              NaN          NaN
4          RWF  2637270          RWF              NaN          NaN

   External FX rate  External service provider
0               NaN                        NaN
1               NaN                        NaN
2               NaN                        NaN
3               NaN                        NaN
4               NaN                        NaN

[5 rows x 54 columns]


==================================================
Showing the first few rows of file: 23rd April to 30th april.csv
==================================================
            Id External id                 Date      Status     Type  \
0  27637850843         NaN  2026-04-30 23:16:14  Successful  Payment
1  27637424041         NaN  2026-04-30 22:16:59  Successful  Payment
2  27637414497         NaN  2026-04-30 22:15:51  Successful  Payment
3  27636486795         NaN  2026-04-30 20:56:06  Successful  Payment
4  27631761657         NaN  2026-04-30 18:17:53  Successful  Cash in

  Provider category                     From  \
0               NaN  FRI:250782001150/MSISDN
1               NaN  FRI:250788471280/MSISDN
2               NaN  FRI:250788694064/MSISDN
3               NaN  FRI:250788300524/MSISDN
4               NaN  FRI:250781028803/MSISDN

                                           From name  \
0                                   Shillah NAYEBARE
1                             Bonaventure Hakizimana
2                                    Cyprien MUPENZI
3                                      Fredy MUSIIME
4  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd

                                   From handler name               To  ...  \
0                                   Shillah NAYEBARE  FRI:21327076/MM  ...
1                             Bonaventure Hakizimana  FRI:21327076/MM  ...
2                                    Cyprien MUPENZI  FRI:21327076/MM  ...
3                                      Fredy MUSIIME  FRI:21327076/MM  ...
4  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd    FRI:827249/ID  ...

  Coupon Currency.13  Amount Currency.14 Balance Currency.15 External amount  \
0    NaN         NaN  146000         RWF  545093         RWF             NaN
1    NaN         NaN    3500         RWF  399823         RWF             NaN
2    NaN         NaN    8000         RWF  396340         RWF             NaN
3    NaN         NaN  250000         RWF  388380         RWF             NaN
4    NaN         NaN -100000         RWF  139630         RWF             NaN

   Currency.16  External FX rate External service provider
0          NaN               NaN                       NaN
1          NaN               NaN                       NaN
2          NaN               NaN                       NaN
3          NaN               NaN                       NaN
4          NaN               NaN                       NaN

[5 rows x 54 columns]


==================================================
Showing the first few rows of file: 25th to 28th march.csv
==================================================
            Id  External id                 Date      Status     Type  \
0  26982643775          NaN  2026-03-28 23:59:33  Successful  Payment
1  26982629953          NaN  2026-03-28 23:56:05  Successful  Payment
2  26982624471          NaN  2026-03-28 23:54:42  Successful  Payment
3  26982572806          NaN  2026-03-28 23:42:42  Successful  Cash in
4  26982566937          NaN  2026-03-28 23:41:25  Successful  Payment

   Provider category                     From  \
0                NaN  FRI:250789814688/MSISDN
1                NaN  FRI:250788221513/MSISDN
2                NaN  FRI:250780613410/MSISDN
3                NaN  FRI:250781028803/MSISDN
4                NaN  FRI:250784973921/MSISDN

                                           From name  \
0                                    Omar NIZEYIMANA
1                                 Fernand RUTABINGWA
2                                   ASPHAT MABENGEZA
3  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd
4                           Jean Charmant HAKIZIMANA

                                   From handler name               To  ...  \
0                                    Omar NIZEYIMANA  FRI:21327076/MM  ...
1                                 Fernand RUTABINGWA  FRI:21327076/MM  ...
2                                   ASPHAT MABENGEZA  FRI:21327076/MM  ...
3  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd   FRI:9175530/ID  ...
4                           Jean Charmant HAKIZIMANA  FRI:21327076/MM  ...

  Coupon Currency.13  Amount Currency.14  Balance Currency.15 External amount  \
0    NaN         NaN    9000         RWF  3645872         RWF             NaN
1    NaN         NaN   12000         RWF  3636917         RWF             NaN
2    NaN         NaN    3000         RWF  3624977         RWF             NaN
3    NaN         NaN  -80000         RWF  3621992         RWF             NaN
4    NaN         NaN  360000         RWF  3701992         RWF             NaN

   Currency.16  External FX rate External service provider
0          NaN               NaN                       NaN
1          NaN               NaN                       NaN
2          NaN               NaN                       NaN
3          NaN               NaN                       NaN
4          NaN               NaN                       NaN

[5 rows x 54 columns]


==================================================
Showing the first few rows of file: 26th feb to 3rd march 2026.csv
==================================================
            Id External id                 Date      Status     Type  \
0  26470835364         NaN  2026-03-03 23:22:09  Successful  Payment
1  26469705552         NaN  2026-03-03 21:25:50  Successful  Payment
2  26467721340         NaN  2026-03-03 20:00:21  Successful  Payment
3  26464243630         NaN  2026-03-03 18:23:12  Successful  Cash in
4  26464164759         NaN  2026-03-03 18:21:00  Successful  Cash in

  Provider category                     From  \
0               NaN  FRI:250781637821/MSISDN
1               NaN  FRI:250785555351/MSISDN
2               NaN  FRI:250789806434/MSISDN
3               NaN  FRI:250781028803/MSISDN
4               NaN  FRI:250781028803/MSISDN

                                           From name  \
0                                       Steven ISHYA
1                                    Emmanuel SHYAKA
2                                  Emmanuel MUHUMUZA
3  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd
4  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd

                                   From handler name               To  ...  \
0                                       Steven ISHYA  FRI:21327076/MM  ...
1                                    Emmanuel SHYAKA  FRI:21327076/MM  ...
2                                  Emmanuel MUHUMUZA  FRI:21327076/MM  ...
3  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd    FRI:668475/ID  ...
4  TERRASSA HOSPITALITY Ltd TERRASSA HOSPITALITY Ltd   FRI:5605540/ID  ...

  Coupon Currency.13  Amount Currency.14 Balance Currency.15 External amount  \
0    NaN         NaN   48000         RWF  951475         RWF             NaN
1    NaN         NaN    1500         RWF  903715         RWF             NaN
2    NaN         NaN  148000         RWF  902223         RWF             NaN
3    NaN         NaN  -31000         RWF  754963         RWF             NaN
4    NaN         NaN  -23500         RWF  785963         RWF             NaN

   Currency.16  External FX rate External service provider
0          NaN               NaN                       NaN
1          NaN               NaN                       NaN
2          NaN               NaN                       NaN
3          NaN               NaN                       NaN
4          NaN               NaN                       NaN

[5 rows x 54 columns]


==================================================
Showing the first few rows of file: 28th to 31st March.csv
==================================================
            Id  External id                 Date      Status     Type  \
0  27043540834          NaN  2026-03-31 22:08:54  Successful  Payment
1  27042453206          NaN  2026-03-31 20:56:14  Successful  Payment
2  27042111478          NaN  2026-03-31 20:40:04  Successful  Payment
3  27042074765          NaN  2026-03-31 20:38:28  Successful  Payment
4  27036174626          NaN  2026-03-31 17:25:58  Successful  Payment


Combining csv files for general cleaning

In [12]:
# 4. Combine them into one single DataFrame
combined_df = pd.concat(df_list, ignore_index=True)

# View the combined data
print(f"Combined DataFrame shape: {combined_df.shape}")

Combined DataFrame shape: (1054, 54)

In [14]:
# 1. Combine all the DataFrames from your list into one single DataFrame
combined_df = pd.concat(df_list, ignore_index=True)

# 2. Print summary information about the data types and missing values
print("--- Data Information Summary ---")
combined_df.info()

print("\n--- Total Rows and Columns ---")
print(f"Rows: {combined_df.shape[0]}, Columns: {combined_df.shape[1]}")

# 3. Print the actual table preview
print("\n--- First 5 Rows of Combined Data ---")
combined_df.head()

--- Data Information Summary ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054 entries, 0 to 1053
Data columns (total 54 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         1054 non-null   int64
 1   External id                9 non-null      object
 2   Date                       1054 non-null   object
 3   Status                     1054 non-null   object
 4   Type                       1054 non-null   object
 5   Provider category          8 non-null      object
 6   From                       1054 non-null   object
 7   From name                  1054 non-null   object
 8   From handler name          1053 non-null   object
 9   To                         1054 non-null   object
 10  To name                    1054 non-null   object
 11  To handler name            1054 non-null   object
 12  To message                 188 non-null    object
 13  Initiated by               180 non-null    object
 14  Initiated by.1             180 non-null    object
 15  On behalf of               180 non-null    object
 16  On behalf of.1             180 non-null    object
 17  Approved by                0 non-null      float64
 18  From / Fee                 0 non-null      float64
 19  Currency                   175 non-null    object
 20  From / External fee        0 non-null      float64
 21  Currency.1                 0 non-null      float64
 22  To / Fee                   849 non-null    float64
 23  Currency.2                 874 non-null    object
 24  To / External fee          0 non-null      float64
 25  Currency.3                 0 non-null      float64
 26  From / Refunded fee        0 non-null      float64
 27  Currency.4                 0 non-null      float64
 28  To / Refunded fee          0 non-null      float64
 29  Currency.5                 0 non-null      float64
 30  From / Taxes               0 non-null      float64
 31  Currency.6                 0 non-null      float64
 32  To / Taxes                 0 non-null      float64
 33  Currency.7                 0 non-null      float64
 34  From / Refunded taxes      0 non-null      float64
 35  Currency.8                 0 non-null      float64
 36  To / Refunded taxes        0 non-null      float64
 37  Currency.9                 0 non-null      float64
 38  Discount                   0 non-null      float64
 39  Currency.10                0 non-null      float64
 40  From / Promotion           0 non-null      float64
 41  Currency.11                0 non-null      float64
 42  To / Promotion             0 non-null      float64
 43  Currency.12                0 non-null      float64
 44  Coupon                     0 non-null      float64
 45  Currency.13                0 non-null      float64
 46  Amount                     1054 non-null   int64
 47  Currency.14                1054 non-null   object
 48  Balance                    1050 non-null   float64
 49  Currency.15                1054 non-null   object
 50  External amount            0 non-null      float64
 51  Currency.16                0 non-null      float64
 52  External FX rate           0 non-null      float64
 53  External service provider  0 non-null      float64
dtypes: float64(32), int64(2), object(20)
memory usage: 444.8+ KB

--- Total Rows and Columns ---
Rows: 1054, Columns: 54

--- First 5 Rows of Combined Data ---

,Id,External id,Date,Status,Type,Provider category,From,From name,From handler name,To,...,Coupon,Currency.13,Amount,Currency.14,Balance,Currency.15,External amount,Currency.16,External FX rate,External service provider
0,26819789562,NaN,2026-03-20 17:50:30,Successful,Payment,NaN,FRI:250784897438/MSISDN,Aline Kayitesi,Aline Kayitesi,FRI:21327076/MM,...,NaN,NaN,1000,RWF,1418386.0,RWF,NaN,NaN,NaN,NaN
1,26814154535,NaN,2026-03-20 13:10:59,Successful,Payment,NaN,FRI:250788312174/MSISDN,Gihana Manasseh WANDERA,Gihana Manasseh WANDERA,FRI:21327076/MM,...,NaN,NaN,13000,RWF,1417386.0,RWF,NaN,NaN,NaN,NaN
2,26813179874,NaN,2026-03-20 12:23:28,Successful,Payment,NaN,FRI:250788301339/MSISDN,Andre MUNYAKAZI,Andre MUNYAKAZI,FRI:21327076/MM,...,NaN,NaN,3000,RWF,1404451.0,RWF,NaN,NaN,NaN,NaN
3,26807177253,NaN,2026-03-20 02:17:21,Successful,Payment,NaN,FRI:250788306609/MSISDN,Emmanuel MUSHINZIMANA,Emmanuel MUSHINZIMANA,FRI:21327076/MM,...,NaN,NaN,260000,RWF,1401466.0,RWF,NaN,NaN,NaN,NaN
4,26807146138,NaN,2026-03-20 01:50:34,Successful,Payment,NaN,FRI:250792416929/MSISDN,Jaques NIZEYIMANA,Jaques NIZEYIMANA,FRI:21327076/MM,...,NaN,NaN,2000,RWF,1142766.0,RWF,NaN,NaN,NaN,NaN

In [15]:
# 1. Define the name of your new master file
output_file = Path("combined_momo_statements.csv")

# 2. Save the combined DataFrame back to your current folder
# index=False prevents Pandas from creating an extra unnamed column for row numbers
combined_df.to_csv(output_file, index=False)

print(f"🎉 Success! Combined file saved in this folder as: '{output_file.name}'")

🎉 Success! Combined file saved in this folder as: 'combined_momo_statements.csv'

Loading the combined file and list the column names

In [16]:
from pathlib import Path
import pandas as pd

# 1. Point to your combined CSV file
file_path = Path("combined_momo_statements.csv")

# 2. Load it into a DataFrame
df = pd.read_csv(file_path)

# 3. Print the initial setup to see what we are starting with
print(f"File loaded successfully!")
print(f"Initial Dimensions: {df.shape[0]} rows and {df.shape[1]} columns.\n")
print("Columns currently in the file:")
print(list(df.columns))

File loaded successfully!
Initial Dimensions: 1054 rows and 54 columns.

Columns currently in the file:
['Id', 'External id', 'Date', 'Status', 'Type', 'Provider category', 'From', 'From name', 'From handler name', 'To', 'To name', 'To handler name', 'To message', 'Initiated by', 'Initiated by.1', 'On behalf of', 'On behalf of.1', 'Approved by', 'From / Fee', 'Currency', 'From / External fee', 'Currency.1', 'To / Fee', 'Currency.2', 'To / External fee', 'Currency.3', 'From / Refunded fee', 'Currency.4', 'To / Refunded fee', 'Currency.5', 'From / Taxes', 'Currency.6', 'To / Taxes', 'Currency.7', 'From / Refunded taxes', 'Currency.8', 'To / Refunded taxes', 'Currency.9', 'Discount', 'Currency.10', 'From / Promotion', 'Currency.11', 'To / Promotion', 'Currency.12', 'Coupon', 'Currency.13', 'Amount', 'Currency.14', 'Balance', 'Currency.15', 'External amount', 'Currency.16', 'External FX rate', 'External service provider']

Droping empty columns into our new file

In [17]:
# 1. Drop columns where ALL values are missing (NaN)
# axis=1 targets columns; how='all' ensures we only drop 100% empty ones
df_clean = df.dropna(axis=1, how="all")

# 2. Calculate and display exactly what changed
removed_cols = set(df.columns) - set(df_clean.columns)

print("--- Cleaning Summary ---")
print(f"Columns removed ({len(removed_cols)}): {list(removed_cols)}")
print(f"Remaining columns ({len(df_clean.columns)}): {list(df_clean.columns)}")
print(f"New Dimensions: {df_clean.shape[0]} rows and {df_clean.shape[1]} columns.\n")

# 3. Preview the cleaned data
df_clean.head()

--- Cleaning Summary ---
Columns removed (30): ['Currency.12', 'To / Refunded taxes', 'Currency.11', 'Currency.9', 'Currency.16', 'From / Fee', 'Coupon', 'Currency.10', 'Currency.8', 'From / Promotion', 'To / Promotion', 'From / Taxes', 'Currency.7', 'To / Refunded fee', 'External amount', 'Currency.4', 'To / External fee', 'Currency.5', 'External service provider', 'From / External fee', 'Currency.3', 'Currency.13', 'From / Refunded taxes', 'From / Refunded fee', 'Currency.6', 'To / Taxes', 'External FX rate', 'Currency.1', 'Approved by', 'Discount']
Remaining columns (24): ['Id', 'External id', 'Date', 'Status', 'Type', 'Provider category', 'From', 'From name', 'From handler name', 'To', 'To name', 'To handler name', 'To message', 'Initiated by', 'Initiated by.1', 'On behalf of', 'On behalf of.1', 'Currency', 'To / Fee', 'Currency.2', 'Amount', 'Currency.14', 'Balance', 'Currency.15']
New Dimensions: 1054 rows and 24 columns.

,Id,External id,Date,Status,Type,Provider category,From,From name,From handler name,To,...,Initiated by.1,On behalf of,On behalf of.1,Currency,To / Fee,Currency.2,Amount,Currency.14,Balance,Currency.15
0,26819789562,NaN,2026-03-20 17:50:30,Successful,Payment,NaN,FRI:250784897438/MSISDN,Aline Kayitesi,Aline Kayitesi,FRI:21327076/MM,...,NaN,NaN,NaN,NaN,NaN,RWF,1000,RWF,1418386.0,RWF
1,26814154535,NaN,2026-03-20 13:10:59,Successful,Payment,NaN,FRI:250788312174/MSISDN,Gihana Manasseh WANDERA,Gihana Manasseh WANDERA,FRI:21327076/MM,...,NaN,NaN,NaN,NaN,65.0,RWF,13000,RWF,1417386.0,RWF
2,26813179874,NaN,2026-03-20 12:23:28,Successful,Payment,NaN,FRI:250788301339/MSISDN,Andre MUNYAKAZI,Andre MUNYAKAZI,FRI:21327076/MM,...,NaN,NaN,NaN,NaN,15.0,RWF,3000,RWF,1404451.0,RWF
3,26807177253,NaN,2026-03-20 02:17:21,Successful,Payment,NaN,FRI:250788306609/MSISDN,Emmanuel MUSHINZIMANA,Emmanuel MUSHINZIMANA,FRI:21327076/MM,...,NaN,NaN,NaN,NaN,1300.0,RWF,260000,RWF,1401466.0,RWF
4,26807146138,NaN,2026-03-20 01:50:34,Successful,Payment,NaN,FRI:250792416929/MSISDN,Jaques NIZEYIMANA,Jaques NIZEYIMANA,FRI:21327076/MM,...,NaN,NaN,NaN,NaN,10.0,RWF,2000,RWF,1142766.0,RWF

Reviewing the cleaning dataset

In [18]:
# 1. Define the name for your newly cleaned dataset
clean_output_file = Path("cleaned_momo_statements.csv")

# 2. Save the cleaned DataFrame back to your current folder
# index=False ensures Pandas doesn't add an unnecessary row-number column
df_clean.to_csv(clean_output_file, index=False)

print(f"🎉 Success! The cleaned dataset has been saved as: '{clean_output_file.name}'")
print("You can now open this file in your folder to review the clean layout.")

🎉 Success! The cleaned dataset has been saved as: 'cleaned_momo_statements.csv'
You can now open this file in your folder to review the clean layout.

Loading again the cleaned saved file

In [19]:
from pathlib import Path
import pandas as pd

# 1. Point to your clean file
clean_file = Path("cleaned_momo_statements.csv")

# 2. Load it into a new DataFrame
df_dates = pd.read_csv(clean_file)

print("File loaded successfully!")
print(f"Current columns available: {list(df_dates.columns)}")

# Let's peek at how the date column looks right now
# Note: Replace 'Date' with the exact name of your column if it's different (e.g., 'date', 'Timestamp')
date_col_name = 'Date' 
print(f"\nCurrent data type of '{date_col_name}': {df_dates[date_col_name].dtype}")
print("First 3 date samples look like this:")
print(df_dates[date_col_name].head(3))

File loaded successfully!
Current columns available: ['Id', 'External id', 'Date', 'Status', 'Type', 'Provider category', 'From', 'From name', 'From handler name', 'To', 'To name', 'To handler name', 'To message', 'Initiated by', 'Initiated by.1', 'On behalf of', 'On behalf of.1', 'Currency', 'To / Fee', 'Currency.2', 'Amount', 'Currency.14', 'Balance', 'Currency.15']

Current data type of 'Date': object
First 3 date samples look like this:
0    2026-03-20 17:50:30
1    2026-03-20 13:10:59
2    2026-03-20 12:23:28
Name: Date, dtype: object

Cell 2: Convert the date column to the right data typeConvert the date column to the right data type

In [20]:
# 1. Define your date column name
date_col_name = 'Date'

# 2. Convert the column to datetime
# dayfirst=True is highly recommended if your dates are formatted like DD/MM/YYYY
df_dates[date_col_name] = pd.to_datetime(df_dates[date_col_name], dayfirst=True)

print(f"✅ Success! New data type of '{date_col_name}': {df_dates[date_col_name].dtype}")
print(f"Earliest date found in file: {df_dates[date_col_name].min()}")
print(f"Latest date found in file: {df_dates[date_col_name].max()}")

✅ Success! New data type of 'Date': datetime64[ns]
Earliest date found in file: 2026-02-15 00:21:46
Latest date found in file: 2026-04-30 23:16:14

C:\Users\jeanm\AppData\Local\Temp\ipykernel_39180\4117532988.py:6: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_dates[date_col_name] = pd.to_datetime(df_dates[date_col_name], dayfirst=True)

In [21]:
# 1. Define your start and end targets
start_date = "2026-01-01"
end_date = "2026-04-30"

# 2. Filter the rows using a boolean mask
# This keeps rows where the date is greater than or equal to Jan 1 AND less than or equal to Apr 30
date_filter = (df_dates[date_col_name] >= start_date) & (df_dates[date_col_name] <= end_date)
df_filtered = df_dates[date_filter]

# 3. Sort by date so it's in chronological order
df_filtered = df_filtered.sort_values(by=date_col_name)

print("--- Filtering Summary ---")
print(f"Rows before date filter: {df_dates.shape[0]}")
print(f"Rows after filtering (Jan-Apr 2026): {df_filtered.shape[0]}")
print(f"New date boundaries: {df_filtered[date_col_name].min()} to {df_filtered[date_col_name].max()}")

# Preview the final filtered data
df_filtered.head()

--- Filtering Summary ---
Rows before date filter: 1054
Rows after filtering (Jan-Apr 2026): 1043
New date boundaries: 2026-02-15 00:21:46 to 2026-04-29 23:55:38

,Id,External id,Date,Status,Type,Provider category,From,From name,From handler name,To,...,Initiated by.1,On behalf of,On behalf of.1,Currency,To / Fee,Currency.2,Amount,Currency.14,Balance,Currency.15
271,26101177857,NaN,2026-02-15 00:21:46,Successful,Payment,NaN,FRI:250788532710/MSISDN,Josephine SHARILA,Josephine SHARILA,FRI:21327076/MM,...,NaN,NaN,NaN,NaN,100.0,RWF,20000,RWF,628508.0,RWF
270,26101181094,NaN,2026-02-15 00:22:35,Successful,Payment,NaN,FRI:250784266662/MSISDN,Lydia ABATONI,Lydia ABATONI,FRI:21327076/MM,...,NaN,NaN,NaN,NaN,60.0,RWF,12000,RWF,640448.0,RWF
269,26101196028,NaN,2026-02-15 00:26:31,Successful,Payment,NaN,FRI:250789554323/MSISDN,Christophe BANGA,Christophe BANGA,FRI:21327076/MM,...,NaN,NaN,NaN,NaN,135.0,RWF,27000,RWF,667313.0,RWF
268,26101198811,NaN,2026-02-15 00:27:15,Successful,Payment,NaN,FRI:250783025866/MSISDN,Marie Gratia BAMURANGE,Marie Gratia BAMURANGE,FRI:21327076/MM,...,NaN,NaN,NaN,NaN,135.0,RWF,27000,RWF,694178.0,RWF
267,26101215297,NaN,2026-02-15 00:31:44,Successful,Payment,NaN,FRI:250788302821/MSISDN,Ryarasa NKURUNZIZA Joseph,Ryarasa NKURUNZIZA Joseph,FRI:21327076/MM,...,NaN,NaN,NaN,NaN,82.0,RWF,16500,RWF,710596.0,RWF

In [ ]:
!pip install openpyxl

In [22]:
# 1. Define the Excel file path
excel_output_file = Path("jan_to_apr_2026_momo.xlsx")

# 2. Export to Excel
# index=False keeps the spreadsheet clean without an extra numbered column
df_filtered.to_excel(excel_output_file, index=False)

print(f"🎉 Successfully exported to Excel!")
print(f"File saved as: '{excel_output_file.name}'")
print("\n👉 STOP HERE: Open this file in Excel, make your edits, save it, and then come back to run the next cell.")

ModuleNotFoundError: No module named 'openpyxl'

In [6]:
import os
print("Python is currently looking inside:", os.getcwd())

Python is currently looking inside: c:\Users\jeanm\Downloads\iConsult\Terrassa village\Terassa Village-20260518T073310Z-3-001\Terassa Village\ETL_Terrassa_village\momo_statements